# Generated by Django 4.2.1 on 2023-05-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_user', models.CharField(max_length=64)),
                ('second_user', models.CharField(max_length=64)),
            ],
        ),
    ]
