# Generated by Django 4.2.1 on 2023-05-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_name',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
    ]
