# Generated by Django 4.2.1 on 2023-05-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_chat_chat_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.CharField(max_length=64)),
                ('to_user', models.CharField(max_length=64)),
                ('time', models.TimeField(default=1683891990.1066844)),
                ('chat_name', models.CharField(max_length=128)),
            ],
        ),
    ]
