# Generated by Django 4.2.1 on 2023-05-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_alter_message_id_alter_message_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.TimeField(default=1683894833.7948885),
        ),
    ]
