# Generated by Django 4.2.1 on 2023-05-12 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_message_text_alter_message_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='time',
        ),
    ]
