# Generated by Django 4.2.1 on 2023-05-22 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='first_user',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='second_user',
            new_name='driver',
        ),
    ]
