# Generated by Django 4.2.1 on 2023-05-22 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0008_rename_user_users_rename_first_user_chat_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat_name',
        ),
        migrations.AddField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='chats.chat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=64),
        ),
    ]
