# Generated by Django 4.2.1 on 2023-05-22 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0009_remove_message_chat_name_message_chat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='to_user',
        ),
    ]
