# Generated by Django 4.2.1 on 2023-05-22 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0010_remove_message_to_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('priority', models.IntegerField()),
                ('status', models.CharField(max_length=64)),
                ('startTime', models.DateTimeField(max_length=64)),
                ('time', models.TimeField()),
                ('endTime', models.DateTimeField()),
                ('department', models.CharField(max_length=64)),
            ],
        ),
    ]
