# Generated by Django 4.2.1 on 2023-05-24 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0011_issue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='username',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='department',
        ),
        migrations.AddField(
            model_name='issue',
            name='responsiblePerson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='chats.users'),
        ),
        migrations.AddField(
            model_name='users',
            name='tgid',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('users', models.ManyToManyField(to='chats.users')),
            ],
        ),
        migrations.AlterField(
            model_name='chat',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.department'),
        ),
    ]
