# Generated by Django 4.2.1 on 2023-05-24 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0013_remove_department_users_users_depatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='driver',
            field=models.IntegerField(null=True),
        ),
    ]
