# Generated by Django 4.2.1 on 2023-05-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0017_chat_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
