# Generated by Django 4.2.1 on 2023-05-26 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0018_alter_department_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='depatment',
            new_name='department',
        ),
    ]
