# Generated by Django 4.2.1 on 2023-05-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0020_alter_chat_user_alter_message_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
