# Generated by Django 4.2.1 on 2023-05-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0021_alter_users_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='tgid',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
