# Generated by Django 4.2.1 on 2023-05-31 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0022_alter_users_tgid'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='tg_chat',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='tgid',
            field=models.IntegerField(null=True),
        ),
    ]
