# Generated by Django 4.2.1 on 2023-05-31 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0023_message_tg_chat_message_tgid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='tg_chat',
        ),
    ]
