# Generated by Django 4.2.1 on 2023-06-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0024_remove_message_tg_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='user',
        ),
        migrations.AddField(
            model_name='chat',
            name='users',
            field=models.ManyToManyField(null=True, to='chats.users'),
        ),
    ]
