# Generated by Django 4.2.1 on 2023-06-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0025_remove_chat_user_chat_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='departmentName',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='users',
            field=models.ManyToManyField(to='chats.users'),
        ),
    ]
