# Generated by Django 4.2.1 on 2023-06-12 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0029_alter_chat_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chats.chat'),
        ),
    ]
