# Generated by Django 4.2.1 on 2023-06-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0030_issue_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='driver',
        ),
        migrations.AlterField(
            model_name='chat',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
