# Generated by Django 4.2.1 on 2023-06-12 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0031_remove_chat_driver_remove_message_driver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='endTime',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='startTime',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='time',
        ),
    ]
