# Generated by Django 4.2.1 on 2023-06-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0032_remove_issue_endtime_remove_issue_starttime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
