# Generated by Django 4.2.1 on 2023-06-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0033_alter_chat_chat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='audioName',
            field=models.CharField(default=None, max_length=1024, null=True),
        ),
    ]
