# Generated by Django 4.2.1 on 2023-06-19 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0036_remove_message_audioname'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='time',
            field=models.IntegerField(default=1687215394.789758),
        ),
    ]
