# Generated by Django 4.2.1 on 2023-06-20 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0037_message_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.CharField(default=1687219440.8110816, max_length=100),
        ),
    ]
