# Generated by Django 4.2.1 on 2023-06-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0039_notification_alter_message_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='bitrixId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.CharField(default=1687721994.289046, max_length=100),
        ),
    ]
