# Generated by Django 4.2.1 on 2023-06-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0040_chat_bitrixid_alter_message_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='chatToSend',
            new_name='bitrixId',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='timeToSend',
            new_name='timeToSendNext',
        ),
        migrations.AddField(
            model_name='notification',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='interval',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notification',
            name='notificatedCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.CharField(default=1687873650.490421, max_length=100),
        ),
    ]
