# Generated by Django 4.2.1 on 2023-06-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0041_notificationtypes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='interval',
            new_name='sendInterval',
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.CharField(default=1687874071.1913176, max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='timeToSendNext',
            field=models.IntegerField(),
        ),
    ]
