# Generated by Django 4.2.1 on 2023-06-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0042_rename_interval_notification_sendinterval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.CharField(default=1687874082.1278067, max_length=100),
        ),
    ]
