# Generated by Django 4.2.1 on 2023-06-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0044_alter_message_time_alter_notification_typeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.CharField(default=1687874189.8915336, max_length=100),
        ),
    ]
