# Generated by Django 4.2.1 on 2023-06-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0045_alter_message_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='bitrixId',
            new_name='lastTimeInteracted',
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.CharField(default=1687899263.7283223, max_length=100),
        ),
    ]
