# Generated by Django 4.2.1 on 2023-06-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0046_rename_bitrixid_notification_lasttimeinteracted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='bitrixId',
            new_name='lastTimeInteracted',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='lastTimeInteracted',
            new_name='bitrixId',
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.CharField(default=1687899393.613094, max_length=100),
        ),
    ]
