# Generated by Django 4.2.1 on 2023-06-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0047_rename_bitrixid_chat_lasttimeinteracted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.CharField(default=1687954090.446546, max_length=100),
        ),
    ]
